language: python

python:
  - "3.4"

install:
  - pip install -r requirements.production.txt --allow-external mysql-connector-python
  - pip install -r requirements.testing.txt

script:
  - flake8 nidhogg tests
  - coverage run --source=nidhogg setup.py test

after_success: coveralls
