# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"

install: pip install -r test_requirements.txt --allow-external mysql-connector-python

script:
  - flake8 nidhogg tests
  - coverage run --source=lsapi setup.py test

after_success: coveralls
